### ISSUE TITLE
Discussion: Support multiple variables

### ISSUE THREAD

**Issue by Sauilitired** [Incendo/cloud#160]
**Context:**
- https://github.com/Incendo/cloud/issues/137
- https://github.com/Incendo/cloud/pull/142

**Description:**
Cloud currently supports having multiple string literals OR a single variable the children of any parent node. This means that  Cloud allows `/command literal1|literal2|literal3` and `/command <argument>` but not `/command literal|<argument>` or `/command <argument1>|<argument2>`

This was done to guarantee that no ambiguous cases can exist in a command tree, which means that we get completely deterministic input evaluation.

This is however a quite major limitation and this decision has been somewhat controversial. The decision is not final and I think it's about time we come to a conclusion.

**Possible Solutions:**

1. We can do nothing and keep the current limitations.

2. We can support multiple literals and a single argument. This has been attempted in pull request #142. This requires that all string literals are parsed before any variable arguments and this restriction should be appended to the library contracts.

3. We can support multiple literals and multiple arguments. This would be the less restrictive path, but has some major problems: how do we handle error feedback when invalid command input is provided? what order do we evaluate the arguments in? how do we deal with platform integrations (most notably, Brigadier)?

The first option is obviously the easiest but appears to be less favourable. The second option is possible as has been demonstrated by @bergerkiller. The third option would be the least restrictive but would probably require a major rework of the library internals. 

All opinions are very welcome!

**Comment by SirYwell** [comment]
I'd prefer the second option.

The limitations to avoid ambiguousity make sense, but checking literals before passing input as an argument is neither a performance issue nor does it depend on any ordering other than literals before argument. When implementing a command of that type, one need to make sure that e.g. all player names still can be used tho.

Having multiple arguments, however, requires a well-defined order of arguments to check and as already mentioned, error handling is way more difficult and such usage would likely have a negative impact on user experience.

**Comment by Sauilitired** [comment]
The people discussing it has largely favoured the second solution. However, some concerns have been brought up regarding this solution and how pattern matching must necessarily introduce additional complexity. The third solution can most likely be removed from the equation.

**Comment by bergerkiller** [comment]
The major problem with the second option (which I chose) is that you have to make sure that the argument portion is never expected to be one of the literals. For instance, if you have a <name> argument with literals overriding it, it means that <name> can never equal one of the literals.

A way around that would be to offer some form of syntax to 'escape' a literal. For example, you could make it so that:
```
/command literal - executes literal
/command "literal" - executes <arg> with "literal" as input
```

But arguably in the ideal case, users will never need to do this. A positive of the second option is that it doesn't hurt anybody not using it. If you hate the idea of literals overriding arguments, well, just don't use it :p

I'm opposed to the idea of supporting multiple ambiguous <argument> commands. It gets messy extremely quickly, and about the only use I can think of involves flags. I haven't ever needed to use this where I couldn't simply replace it with just one <argument> with a parser that deals with this ambiguity. You also risk obscuring real issues, such as accidentally registering a command twice or making a mistake with the command signature. I know I really want to get an ambiguous command exception when this happens.
