### ISSUE TITLE
Command senders are suggested commands which they cannot use

### ISSUE THREAD

**Issue by jpenilla** [Incendo/cloud#202]
If a specific sender type is set for a command, this is not taken into account for suggestions. For example, if the specific sender type is `Player`, our command will still be suggested in the console, even though console cannot execute this command. Command syntax strings have a similar issue with showing commands not usable by that user.

**Comment by Citymonstret** [comment]
This should probably be done using a predicate permission. The reason for this is that we need brigadier to filter out the nodes that the sender shouldn't have access to. We do a permission check here:
https://github.com/Incendo/cloud/blob/e73c9a3bafe66a4c3846be57825ae4e8ef2ed868/cloud-minecraft/cloud-brigadier/src/main/java/cloud/commandframework/brigadier/CloudBrigadierManager.java#L469

As long as sender types are checked before permissions when executing commands we'll still get the correct exception. If it fails because of the sender type being wrong, it won't do the permission check and permissions can then only fail due to the existing permission node.
