### ISSUE TITLE
IntegerArgument uses Integer as the default value and I want to specify the minimum value.

### ISSUE THREAD

**Issue by book000** [Incendo/cloud#241]
Thank you for creating a great framework. I'm using this framework to create PaperMC plugin commands.

In a certain command, I thought about implementing pagenation to display a list of items.
In general, we believe that the commands that should be implemented are as follows:

- `/items list`: Display items on the first page.
- `/items list <page>`: Show items on the specified page. (e.g. `/items list 2`)
  - and the `<page>` expects the following: More than `1`

I was hoping that I could implement it with the following, but it did not work.

```java
IntegerArgument
  .optional("page", 1)
  .withMin(1) // <- CommandArgument does not have withMin.
```

If you use newBuilder, you can do withMin, but you cannot use the default value. In the following, an error occurs because asOptionalWithDefault does not take Integer as an argument.

```java
IntegerArgument
  .newBuilder("page")
  .asOptionalWithDefault(1) // <- Required type: String / Current type: int
  .withMin(1)
```

What can I do to make it the format I expect?
Sorry for the poor English. I look forward to your reply.

**Comment by jpenilla** [comment]
You need to the do the `IntegerArgument.Builder`-specific methods first.
```java
IntegerArgument.<CommandSender>newBuilder("page")
    .withMin(1)
    .asOptionalWithDefault("1")
    .build();
```
This is because `asOptionalWithDefault` is an inherited method from `CommandArgument.Builder`, and returns that type, not `IntegerArgument.Builder`.

With the way the command pipeline works currently, defaults need to be a string. In some places, we have convenience methods for creating command arguments with strongly typed defaults, however they all just serialize to a string. For example:
https://github.com/Incendo/cloud/blob/6952f7d3bf6dfb6228f78336855ca23ac6fcbd1e/cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/argument/ColorArgument.java#L102-L110

**Comment by book000** [comment]
Thank you for your specific reply.

I was able to understand how to do that. However, I want to implement it type-safely, so I hope it will be supported in the future.

The question has been resolved, so I will close it. thank you for answering.:blush:
