### ISSUE TITLE
MultiplePlayerSelector can only handle one player

### ISSUE THREAD

**Issue by Distractic** [Incendo/cloud#431]
I have this command :

```kt
    @CommandMethod("teams set <team> <players>")
    fun setTeams(
        commandSender: CommandSender,
        @Argument("team") teamId: Int,
        @Argument("players") playerSelector: MultiplePlayerSelector,
    ) { 
       // ...
    }
```

So, when I try to add several players, the auto-completion works only for the first player's name.
Also, I can only add one player.

![image](https://user-images.githubusercontent.com/46402441/222612792-080215f8-87e8-4563-9585-994122610511.png)

![image](https://user-images.githubusercontent.com/46402441/222612724-8a6d44b3-e0c1-478f-a1c0-89304d06c712.png)
6402441/222612692-4321b0fe-af14-4e7e-8d9a-1a5ce934dd7a.png)

**Comment by jpenilla** [comment]
That's not how the MultiplePlayerSelector works, it allows selecting multiple players using `@` syntax[ like in vanilla commands](https://minecraft.fandom.com/wiki/Target_selectors). I recommended it on Discord as an alternate solution, didn't say it does exactly what you wanted.

To do what you're describing you'd need a custom parser that you map to greedy string on the BrigadierManager. All of this is a repeat of what I said on Discord, so not sure what the point of the issue is.
